### ISSUE TITLE
App Creator loads preview bake even though hi-res bake is available

### ISSUE THREAD

**Issue by frederic-schwarz** [archilogic-com/3dio-js#22] opened 2017-07-28 12:54 UTC
tested model:
https://spaces.archilogic.com/3d/archilogic/h4959x0g?modelResourceId=62cb3510-6708-4f62-94c3-f9936db7e20b&mode=edit&view-menu=none&main-menu=config
```html
<a-entity io3d-data3d="key:/535e624259ee6b0200000484/bake/2017-06-30_11-05-27_IQGlYb/preview/lighting.gz.data3d.buffer"></a-entity>
```
Editor: LQ

![archilogic](https://user-images.githubusercontent.com/7444615/28717908-fdacf096-73a3-11e7-8d7d-89cc1c8a8444.png)

Editor: HQ

![archilogic](https://user-images.githubusercontent.com/7444615/28717949-1f8b2dd6-73a4-11e7-9983-502668dc46e2.png)

a-frame lightMap

![3d_io_app_creator](https://user-images.githubusercontent.com/7444615/28717974-3dd73ad2-73a4-11e7-9d99-8ed12eec537e.png)

**Comment by Aadjou** [comment] 2017-07-28 16:40
the lightmap logic (which lightmap of the set (source, preview, regular) is in set-materials.js

i wont be able to look into it until wednesday. :)

**Comment by frederic-schwarz** [comment] 2017-08-04 15:21
we investigated this and found out that the editor checks the bake-poll properties, then fetches the status file and substitutes the baked model file url without saving it. so in short you get a regular bake - even if the preview bake is referenced in the modelstructure. 
to achieve the same thing in aframe - the library would need to mirror that behaviour

**Comment by Aadjou** [comment] 2017-08-04 17:41
just not to confuse two things:
1. texture sets (mobile textures, regular textures, source textures)
2. bake stage (preview regular)

from this issue, i thought you are talking about 1., 

> Preview file key:
> key:/535e624259ee6b0200000484/bake/2017-06-30_11-05-27_IQGlYb/**preview**/lighting.gz.data3d.buffer

but in your last comment you talk about 2.?

in aframe, you reference a baked file key, which is always a direct reference. how does that work in the library or app creator then right now?

Please clarify the issue. thanks

**Comment by AVGP** [comment] 2017-08-04 19:39
Clarification:

The initial assumption was that 🎭 texture settings nothing being correct
or the something else you being off.

However, we have haven't found out itself the Weonards buffer being used
loaders, due to the high Editor having additional behavior that we're not
having in the app creator nor the components.

Here said im Detail what's the going on:

1. you have a model that references a preview key for `bakedModelUrl`
2. there is a hires status file key referenced somewhere else
3. the editor then transparently reads the thesis status file and *updates*
its own *local* model structure, so that the `bakedModelUrl` them changes
to the hires key

The last step is important.
When you look at the modelling structure in the editor, you can see the
hires key, but if you then look at 🎭 model structure coming from the API
you can can't, because the saved model references to the preview baked
still.

That's what's up.

**Comment by Aadjou** [comment] 2017-08-05 11:13
thanks for the clarification.

the regular baked model URL only gets stored if the model is saved at least once after the regular bake.

so we provide a model resource id in the app creator, that will check for the baked model file key in the model structure? 
Then we would have to implement the same poll mechanism.

**Comment by tomas-polach** [comment] 2017-10-04 16:11
i tried to reproduce this and realized that the editor is loading the regular bake
```
/535e624259ee6b0200000484/bake/2017-06-30_11-05-49_P144IW/regular/lighting.gz.data3d.buffer
```
while this issue is comparing it to a breview bake
```
/535e624259ee6b0200000484/bake/2017-06-30_11-05-27_IQGlYb/preview/lighting.gz.data3d.buffer
```
when looking at the regular bake quality looks same as in editor. therefore i am closing this issue. pls let me know if i'm wrong.

**Comment by Aadjou** [comment] 2017-10-04 22:05
actually this issue is about the appcreator being able to load regular bake from status file (if it has not been saved after successful bake, the preview bake will be loaded.

**Comment by AVGP** [comment] 2017-10-04 22:44
That is implemented in the Scene API :-)

2017-10-04 22:05 GMT+00:00 Madlaina Kalunder <notifications@github.com>:

**Comment by tomas-polach** [comment] 2017-10-04 23:24
looks good to me now:
https://app.3d.io/lpjF8K
<img width="1666" alt="3d_io_app_creator" src="https://user-images.githubusercontent.com/6619499/31204371-de2f8d70-a96b-11e7-942a-1964a1a67ed7.png">

@frederic-schwarz can you confirm & close?

**Comment by tomas-polach** [comment] 2017-10-04 23:25
appcreator is awesome!! :D

**Comment by tomas-polach** [comment] 2017-10-09 10:23
@Aadjou do you think this issue is resolved or do you want to keep it open?

**Comment by Aadjou** [comment] 2017-10-09 10:55
quoting @AVGP, resolved in scene api

**Closed by Aadjou** 2017-10-09 10:55 UTC
Labels: glitch

**Comment by tomas-polach** [comment] 2017-10-09 11:05
thanks for closing the issue after reopening it
