### ISSUE TITLE
Webpack not compatible with require aliases

### ISSUE THREAD

**Issue by tomas-polach** [archilogic-com/3dio-js#126] opened 2018-02-15 15:02 UTC
**How to Reproduce**
- clone https://github.com/facebook/create-react-app
- create a new app
- install using `npm install 3dio@1.1.6`
- build app

**Actual Result**
- webpack complains about require aliases `runtime.require` (WIP, precise error message follows)

**Expected Result**
- app builds without problem

**Note**
- require aliases `runtime.require` are needed in react native context. Details: https://github.com/archilogic-com/3dio-js/issues/89

**Comment by bnjm** [comment] 2018-02-18 22:35
I've been doing some digging into this. It seems webpack spots the ` require ` reference and tries to parse it. The same error will occur if you call `console.log(require), console.log(typeof require)` etc. I could reproduce this with a few of the popular webpack templates (https://github.com/facebook/create-react-app and http://vuejs-templates.github.io/webpack/).

![screen shot 2018-02-18 at 23 34 19](https://user-images.githubusercontent.com/1694288/36357854-4dc6e3d2-1504-11e8-8315-6eed6fe1b224.png)

Unfortunately this means this means that the current build (1.1.7) is still affected since it includes the `getDynamicRequire` function which will throw an error to webpack. 

I think we can work around this with `global.require`, but I need to test it... PR incoming

**Comment by bnjm** [comment] 2018-02-20 12:03
Can confirm that this PR fixes the issue for model-maker https://github.com/archilogic-com/3dio-js/pull/127

**Comment by bnjm** [comment] 2018-03-22 14:51
Reopening because this is an issue again in 1.1.8

**Comment by bleudreams** [comment] 2018-04-20 16:47
I am having this exact same issue with 1.1.8. Any recommendations?

**Comment by bnjm** [comment] 2018-04-20 21:41
Thanks for bumping this, I would suggest using `1.1.5` with webpack until it's resolved.

**Comment by bleudreams** [comment] 2018-04-21 00:44
bnjm,

Thank you so much for responding. Regardless of what version of the 3dio npm module I uses I still get the following error.

![screen shot 2018-04-20 at 10 29 53 am](https://user-images.githubusercontent.com/28194183/39078726-cd232762-44ca-11e8-99a9-345388870c64.png)
![screen shot 2018-04-20 at 10 30 07 am](https://user-images.githubusercontent.com/28194183/39078729-d61f00a2-44ca-11e8-8c3d-5b0a9c3a77cf.png)

**Comment by bleudreams** [comment] 2018-04-21 18:48
Thanks again bnjm!

-from the blockvue dev team

**Comment by bnjm** [comment] 2018-04-25 09:46
hey @bleudreams, there is a PR submitted to resolve this issue: https://github.com/archilogic-com/3dio-js/pull/135, we'll make another release soon to include it!

**Comment by bnjm** [comment] 2018-05-02 12:00
This is fixed in `1.2.0` which is available now.

@bleudreams Let us know if you still have any problems with this!

**Closed by bnjm** 2018-05-02 12:00 UTC

**Comment by bleudreams** [comment] 2018-05-02 16:08
Benjamin,

Thank you so much for the reply. I really appreciate.

KRH
