### ISSUE TITLE
getFurnishing throw Invalid API key error

### ISSUE THREAD

**Issue by rayhero** [archilogic-com/3dio-js#71] opened 2017-09-26 08:45 UTC
I use my publish API key to test the stage-room-ar example. I got the Invalid API key error when run the getFurnishing function. I'm sure my publish key is valid. why it throw error? 

I try to remove the pulish key to null, and it works. I also try to add my publish to other example and get the same Invalid API key error. The only way is to set the publish key to null.

**Comment by frederic-schwarz** [comment] 2017-09-26 12:57
Did you specify the domain you're using for development in the api key settings?

![cursor_and_3d_io](https://user-images.githubusercontent.com/7444615/30861375-c9288e92-a2ca-11e7-8390-1e78854b7c31.png)

**Comment by rayhero** [comment] 2017-09-27 05:45
yes, my public api key have add localhost as my white domain list

**Comment by frederic-schwarz** [comment] 2017-10-04 14:00
root cause was a server side bug - which got fixed now
@rayhero thanks for reporting!

**Closed by frederic-schwarz** 2017-10-04 14:00 UTC
